name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libudev
      run: |
        sudo apt update
        sudo apt install libudev-dev
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/release/remote_serial
    - name: Run tests
      run: cargo test --verbose
